
# enable Docker for your repository
options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          name: run-test
          image: node:10-alpine
          script:
            - npm install
            # - npm run test-integration

  tags:
    release-production-*:
      - step:
          name: Build - Push - Deploy to GCP (gcr.io/YourGoogleProject/YourCloudRunServiceName) for Production
          image: google/cloud-sdk:latest
          caches:
            - docker
          deployment: production
          script:
            # set CLOUDSDK_CONFIG environment variables
            # - export CLOUDSDK_CONFIG=`pwd`/credentials/service-account.json
            # - gcloud config list

            # set image name
            - export IMAGE_NAME=$HOSTNAME/$PROJECT_ID/appsbymatthew # ex. gcr.io/my-g-project/my-cr-service 
            - export SERVICE_NAME=$SERVICE_NAME

            # Build image
            - docker build -t $IMAGE_NAME .

            # Gcloud auth and check
            - gcloud auth activate-service-account bitbucket-pipeline@bar.iam.gserviceaccount.com --key-file=credentials/service-account.json
            - gcloud config list

            # config image registry with gcloud helper
            - gcloud auth configure-docker -q

            # push image to gcr
            - docker push $IMAGE_NAME

            # deploy to cloud run
            - gcloud beta run deploy $SERVICE_NAME --image $IMAGE_NAME --region us-central1 --project $GOOGLE_PROJECT_ID
